### ISSUE TITLE
The python is wrong in the introduction

### ISSUE THREAD

**Issue by olynch** [RedPRL/yuujinchou#127]
The introduction says

> This library was motivated by the name modifiers in the "import" or "include" statements present in all practical programming languages:

```python
import math # Python: the sqrt function is available as `sqrt`.
```

If you want the behavior of bringing `sqrt` into scope, it should be

```python
from math import *
```

**Comment by favonia** [comment]
@olynch Thank you! Closed by f5f6a32eea438891c08a018a827f606c66b5a7c3
